### ISSUE TITLE
无法达到预期精度

### ISSUE THREAD

**Issue by saysth** [Lornatang/pytorch-inception-v3-cifar100#1]
您好，train结束时loss仍在2点多，validation精度仅20%+，无法达到您说的acc0.94，请问是哪里出了问题吗？

**Comment by Lornatang** [comment]
Let me see you code. @saysth

**Comment by saysth** [comment]
[train.txt](https://github.com/Lornatang/pytorch-inception-v3-cifar100/files/3885476/train.txt)
[net.txt](https://github.com/Lornatang/pytorch-inception-v3-cifar100/files/3885477/net.txt)
[validation.txt](https://github.com/Lornatang/pytorch-inception-v3-cifar100/files/3885478/validation.txt)

由于上传文件不支持.py格式，我改成.txt了。train.py中把device指定cuda没报错，但validation时报错RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same，所以device改用了CPU。

**Comment by saysth** [comment]
您好，请问问题出在什么地方呢？ @Lornatang

**Comment by Lornatang** [comment]
Problems with model and GPU training @saysth

**Comment by saysth** [comment]
i didn't change your model. maybe it's the problem of GPU training. do you think it's the problem with versions of modules? could you provide the versions of torch, CUDA and other key modules that can correctly run your code? Thank you!

**Comment by Lornatang** [comment]
Pytorch:1.4 
torchvision:0.4 
CUDA:10.1

**Comment by Lornatang** [comment]
I will update the code tomorrow to fix your feedback. @saysth

**Comment by Lornatang** [comment]
Code is update. @saysth
